# Generated by Django 2.0.6 on 2018-06-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('threads', models.IntegerField(default=0)),
                ('posts', models.IntegerField(default=0)),
            ],
        ),
    ]
