# Generated by Django 2.0.6 on 2018-06-07 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_trade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='tile',
            new_name='title',
        ),
    ]
