# Generated by Django 2.0.1 on 2018-06-12 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180607_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='WonList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Trade')),
            ],
        ),
    ]
