# Generated by Django 2.0.1 on 2018-06-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_wonlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='home_id',
            field=models.CharField(default='0', max_length=255, unique=True),
        ),
    ]
