# Generated by Django 2.0.1 on 2018-06-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_trade_home_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='home_id',
            new_name='url_id',
        ),
        migrations.AddField(
            model_name='wonlist',
            name='url_id',
            field=models.CharField(default='0', max_length=255, unique=True),
        ),
    ]
