# Generated by Django 2.0.1 on 2018-06-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20180612_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wonlist',
            name='trade',
        ),
        migrations.AddField(
            model_name='wonlist',
            name='trade_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
