# Generated by Django 2.0.1 on 2018-06-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20180612_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='id',
        ),
        migrations.RemoveField(
            model_name='wonlist',
            name='id',
        ),
        migrations.AlterField(
            model_name='trade',
            name='url_id',
            field=models.CharField(default='0', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wonlist',
            name='url_id',
            field=models.CharField(default='0', max_length=255, primary_key=True, serialize=False),
        ),
    ]
