# Generated by Django 2.0.1 on 2018-06-12 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20180612_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='url_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='wonlist',
            old_name='url_id',
            new_name='id',
        ),
    ]
