# Generated by Django 2.0.1 on 2018-06-12 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20180612_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wonlist',
            name='trade_id',
        ),
        migrations.AddField(
            model_name='wonlist',
            name='trade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Trade'),
            preserve_default=False,
        ),
    ]
