# Generated by Django 2.0.1 on 2018-06-16 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20180612_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.CharField(default='0', max_length=255, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PostDetail',
            fields=[
                ('id', models.CharField(default='0', max_length=255, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('mate_desc', models.CharField(max_length=255)),
                ('mate_key', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PostList',
            fields=[
                ('id', models.CharField(default='0', max_length=255, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='postdetail',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.PostList'),
        ),
    ]
