# Generated by Django 2.0.1 on 2018-06-16 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20180616_1455'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePage',
            new_name='PostHome',
        ),
    ]
