# Generated by Django 2.0.1 on 2018-06-16 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20180616_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdetail',
            name='title',
        ),
        migrations.RemoveField(
            model_name='postdetail',
            name='trade',
        ),
        migrations.RemoveField(
            model_name='postdetail',
            name='url',
        ),
        migrations.AddField(
            model_name='postdetail',
            name='postList',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.PostList'),
            preserve_default=False,
        ),
    ]
