# Generated by Django 2.0.1 on 2018-06-16 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20180616_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdetail',
            name='postList',
            field=models.OneToOneField(default='0', on_delete=django.db.models.deletion.CASCADE, to='polls.PostList'),
        ),
    ]
