# Generated by Django 2.0.1 on 2018-06-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20180616_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='posthome',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
