# Generated by Django 2.0.1 on 2018-06-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_posthome_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdetail',
            name='mate_desc',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='postdetail',
            name='mate_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
