# Generated by Django 2.0.1 on 2018-06-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20180616_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdetail',
            name='mate_desc',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='postdetail',
            name='mate_key',
            field=models.CharField(max_length=255),
        ),
    ]
