# Generated by Django 2.0.1 on 2018-06-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20180616_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdetail',
            name='url',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
