# Generated by Django 2.0.1 on 2018-06-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_postdetail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdetail',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
